### PR TITLE
Adds zenoh-plugin

### PR DESCRIPTION
**Pull request by teburd**
* Adds zenoh-c to our nix packages
* Adds a zenoh-plugin
* Cleans up a few minor CMakeLists.txt leftovers from removing conan
  support

Signed-off-by: Tom Burdick <tom@openenergysolutionsinc.com>

### CODE REVIEW

**Review by corynguyenfl — COMMENTED** [review]
Looks good.  Just ZenohOptions.h might be copied over from NATS?

**Comment by teburd** [comment]
Yes, that is unused, will remove. Good eye

**Comment by teburd** [comment]
Ok sorted out the cross compile bits, had to learn a bit more of how nix works with its cross compile setup.

In essence the targetSystem is a map of values with metadata about the target for cross compile, targetSystem.config holds an llvm triplet like armv7l-unknown-linux-musleabihf  (arch, os, abi (libc)) and that stuff can be picked apart in the targetSystem.parsed attribute.

Rust needed armv7-unknown-linux-musleabihf and so I had to map the target line for that. Now it works well.

**Comment by teburd** [comment]
This builds, I need to update the cached deps so actions doesn't time out.

**Pull request merged**
